name: dash_maze_runner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  confetti: ^0.7.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_vision: ^1.1.4
  google_mlkit_text_recognition: ^0.12.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/launcher_icons/

  fonts:
    - family: theren
      fonts:
        - asset: assets/fonts/TherenRegular.ttf
    - family: super_boys
      fonts:
        - asset: assets/fonts/SuperBoys.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/android/play_store_512.png"
  adaptive_icon_background: "assets/launcher_icons/android/res/mipmap-xxxhdpi/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/launcher_icons/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png"
  min_sdk_android: 21

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  color: "#36c7ff"
  
  android_12:
    # Splash screen background color.
    color: "#36c7ff"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  ios: true
  #web: false